### ISSUE TITLE
Step-by-Step stage 2 

### ISSUE THREAD

**Issue by kellian-cottart** [InseeFrLab/legacy-onyxia-entrypoint#35]
# Step-by-Step 

## Description 

In the `Step-by-Step` guide, the values procured for the second step [here](https://github.com/InseeFrLab/onyxia/blob/main/step-by-step/values/2-oidc.yaml) are not corresponding to the values of the tutorial. They are for the deployment on `sspcloud` instead of being for `onyxia-demo`.

## Proposed fix

```yaml
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: onyxia.demo.insee.io
ui:
  image:
    name: inseefrlab/onyxia-web
  env:
    KEYCLOAK_REALM: sspcloud
    KEYCLOAK_CLIENT_ID: onyxia
    KEYCLOAK_URL: https://auth.lab.sspcloud.fr/auth
api:
  env:
    keycloak.realm: sspcloud
    keycloak.auth-server-url: https://auth.lab.sspcloud.fr/auth
    authentication.mode: "openidconnect"
    springdoc.swagger-ui.oauth.clientId: onyxia
```

Should become 

```yaml
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: onyxia.demo.insee.io
ui:
  env:
    KEYCLOAK_REALM: onyxia-demo
    KEYCLOAK_CLIENT_ID: onyxia-client
    KEYCLOAK_URL: https://keycloak.demo.insee.io/auth
api:
  env:
    keycloak.realm: onyxia-demo
    keycloak.auth-server-url: https://keycloak.demo.insee.io/auth
    authentication.mode: "openidconnect"
    springdoc.swagger-ui.oauth.clientId: onyxia-client
```
